
/*
 * THIS FILE WAS GENERATED BY tools/process_templates.py FROM netflix.js.template.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * 
 * INSTEAD, EDIT netflix.js.template OR tools/selectors.txt AND RUN 
 * tools/process_templates.sh.
 */

/*
 * ContentScripts/netflix.js is a Content Script
 * (https://developer.chrome.com/extensions/content_scripts) which is injected
 * into any netflix.com tab. It's responsible for receiving messages from
 * EventPages/netflix.js and performing a suitable action (such as toggling if
 * blur is enabled or not).
 */

chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
	if (request.name == "toolbarItemClicked") {
		toggleElementBlur();
	}
});

var noBlurStyleNode = null;

function toggleElementBlur() {
	// To disable blur we add a <style> element to the page which contains a
	// `filter: none !important` style for all the selectors that we've
	// previously added a blur to. This new style takes precedence over the old
	// style.
	// We need to use the same selectors to make sure that the noblur style
	// takes precedence, e.g. we can't just set the filter to none on the `body`
	// selector (even if we use `!important`). 
	if (noBlurStyleNode == null) {
		noBlurStyleNode = document.createElement("style");
		noBlurStyleNode.innerHTML = ".PlayerControlsNeo__all-controls > div > .evidence-overlay > p:first-of-type, .episode-list .synopsis, .next-episode .synopsis, .billboard .synopsis, .bob-card .synopsis, .jawbone-overview-info .synopsis, .episodeSynopsis, .simsSynopsis, .WatchNext-episode-synopsis, .PromotedVideo-synopsis { filter: none !important; }";
	}

	var blurEnabled = !toggleNode(noBlurStyleNode);
	if (blurEnabled) {
		displayNotification("Summaries hidden");
	} else {
		displayNotification("Summaries revealed");
	}
}

function toggleNode(node) {
	if (node.parentNode) {
		node.parentNode.removeChild(node);
		return false;
	} else {
		document.body.appendChild(node);
		return true;
	}
}

var notificationNode = null;
var notificationTimeoutID = null;

function displayNotification(message) {
	if (notificationNode == null) {
		notificationNode = document.createElement("div");
		notificationNode.className = "nosummaryforyou-extension-notification";
	}
	notificationNode.innerText = message;

	if (notificationNode.parentNode == null) {
		document.body.appendChild(notificationNode);
	}

	if (notificationTimeoutID) {
		window.clearTimeout(notificationTimeoutID);
	}

	notificationTimeoutID = window.setTimeout(function() {
		notificationNode.parentNode.removeChild(notificationNode);
	}, 3000);
}

